### ISSUE TITLE
404 widgets/ColorPicker.css.map not found

### ISSUE THREAD

**Issue by coonsat** [mendixlabs/color-picker#5]
I'm rendering multiple color pickers by means of objects in a list. The color pickers works as normal for the first object but then throws the following console error for every subsequent colorPicker object: 404 - file not found for file: widgets/ColorPicker.css.map. I've tried to debug this myself but the code is somewhat encrypted.

**Comment by Andries-Smit** [comment]
Widgets are minified and transformed, the source map file is not needed to function. it only cause a console message. The reference should not have been in. Let me check if i can remove it.

**Comment by Andries-Smit** [comment]
Will be fixed in next release, no date expected.
The repository has moved, this feature request is moved to our internal backlog.
