### ISSUE TITLE
How to use `onChange` event?

### ISSUE THREAD

**Issue by pzmudzinski** [mendixlabs/color-picker#7]
I've setup everything in my form and then trying to listen for changes whenever user chooses new color.

I've created new nanoflow and added entity type as a parameter and created JavaScript action but it's never gets called. What should be parameter for nanoflow? String? Entity? Something else? 

I see in source code it's using change handler coming from `react-color` so I have no idea how to convert to Mendix world.

**Comment by pzmudzinski** [comment]
Ok. I take it back. So I was checking if my JS action is called by putting `console.log` inside it. For some reason it's not working, but function itself is called. We can close it.

**Comment by Andries-Smit** [comment]
ok, cheers! We moved the repo, next time if you have an issue you can report it to the mx forum, Support or via https://github.com/mendix/widgets-resources
